services:
  - type: web
    name: real-learn
    runtime: image
    plan: free
    image:
      url: DOCKER_IMAGE_URL_HERE
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_ORIGIN
        value: https://reallearn.site
      - key: CLERK_FRONTEND_API
        value: https://clerk.reallearn.site
      - key: CLERK_API_URL
        value: https://api.clerk.com
      - key: CEREBRAS_API_KEY
        sync: false
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: PORT
        value: "10000"
