// Shared body for the standalone /legal/terms/ route and the /legal hub embed.
// Lives outside page.tsx because Next.js pages may not carry extra exports
// or custom props.

// `embedded` = rendered inside the /legal hub (which owns the page h1);
// the standalone route renders the title as the document h1 instead.
export function TermsOfServiceContent({ embedded = false }: { embedded?: boolean }) {
  const Title = embedded ? ("h2" as const) : ("h1" as const);
  return (
    <article
      style={{
        background: "var(--bg-card)",
        borderRadius: "var(--radius-lg)",
        padding: "32px 28px",
        border: "1px solid var(--border-subtle)",
        lineHeight: 1.7,
      }}
    >
      <Title
        style={{
          fontFamily: "var(--font-display)",
          fontWeight: 700,
          fontSize: 24,
          marginBottom: 16,
        }}
      >
        Terms of Service
      </Title>
      <p style={{ fontSize: 13, color: "var(--text-tertiary)", marginBottom: 24 }}>
        Last updated: August 17, 2026 (version 3.3)
      </p>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>1. Acceptance of Terms</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          By accessing or using RealLearn (&quot;the Service&quot;), you agree to be bound by these Terms of Service
          (&quot;Terms&quot;). If you do not agree to these Terms, you may not use the Service. These Terms
          apply to all visitors, users, and others who access or use the Service.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>2. Description of Service</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          RealLearn is an AI-powered educational platform that generates learning content for
          user-requested topics in two answer modes: &quot;Fast&quot; (a single direct answer part
          with a quick quiz) and &quot;Explain&quot; (a 3-part learning journey — Foundation,
          Mechanism, Real World). The service includes
          interactive quizzes, progress tracking, and multilingual support. It also includes
          optional engagement features — experience points (XP), levels, daily learning streaks,
          daily goals, achievement badges, and shareable result cards — that are stored locally on
          your device to help you build a learning habit. Your saved lesson history is likewise
          stored only on your device (full lesson content in browser IndexedDB, with a lightweight
          history index in localStorage) — clearing your browser&apos;s site data therefore removes
          your saved lessons, and we cannot restore them (re-opening such an entry generates the
          lesson again). The service also includes optional learning personalization: signed-in
          users may choose learning-style preferences and add free-text notes (capped at 500
          characters) that are stored only on their device and included with each lesson-generation
          request to tailor the response; this information is not stored on our servers. The service
          also includes optional voice features: microphone voice input (powered by your browser&apos;s
          built-in speech recognition) and &quot;Listen&quot; read-aloud (audio generated by our
          servers using Microsoft&apos;s Edge text-to-speech service). To improve speed, lessons may
          be served from a short-lived, anonymous server-side cache when the same question has
          recently been asked. The service also builds a <strong>personalized learning profile</strong>
          from your quiz results: a compact, on-device map of the concepts you have proven you know
          and where you are still building confidence, computed on your device. When you ask a
          question, a small, topic-relevant learning-context summary is generated on your device and
          attached to that lesson request so the AI can personalize the answer; this summary is not
          stored on our servers (see the Privacy Policy). There is no separate page to browse or
          manage this profile — it works automatically in the background. The AI&apos;s personalized
          responses are provided &quot;as is&quot; without any
          guarantee of accuracy, completeness, or suitability. RealLearn is intended for educational
          purposes only.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>3. Eligibility and Age Requirements</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          You must be at least <strong>13 years old</strong> to use this Service (or older where your
          jurisdiction sets a higher minimum digital-consent age). By using RealLearn, you represent
          and warrant that you meet this age requirement. If you are under 18, you confirm that you
          have your parent or guardian&apos;s permission — and, where the law requires verifiable
          parental consent for minors (for example, under India&apos;s DPDP Act or COPPA), that such
          consent has been given. We do not knowingly allow children under 13 to create accounts or
          use this Service.
        </p>
        <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
          During onboarding we collect only an age bracket (under 13, 13–17, or 18+), not your exact
          date of birth. Users aged 13–17 must confirm that a parent or legal guardian has reviewed
          and approved their use of RealLearn. Parents or guardians may review the minor&apos;s data,
          revoke consent, request correction or deletion, or raise concerns by contacting us at{" "}
          <a href="mailto:esamzai365@gmail.com" style={{ color: "var(--accent)" }}>
            esamzai365@gmail.com
          </a>
          . See Section 19 of our Privacy Policy for how we handle children&apos;s data.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>4. User Accounts</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          You are responsible for safeguarding your account credentials (managed via Clerk). You
          agree to notify us immediately of any unauthorized use of your account. We are not liable
          for any loss or damage arising from your failure to comply with this security obligation.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>5. Acceptable Use</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)", marginBottom: 8 }}>
          You agree not to use the Service:
        </p>
        <ul style={{ fontSize: 14, color: "var(--text-secondary)", paddingLeft: 20, margin: 0 }}>
          <li style={{ marginBottom: 4 }}>For any unlawful purpose or in violation of any laws.</li>
          <li style={{ marginBottom: 4 }}>To harass, abuse, or harm another person or entity.</li>
          <li style={{ marginBottom: 4 }}>To generate content that is harmful, violent, sexually explicit, or discriminatory.</li>
          <li style={{ marginBottom: 4 }}>To interfere with or disrupt the integrity or performance of the Service.</li>
          <li style={{ marginBottom: 4 }}>To attempt to gain unauthorized access to the Service or related systems.</li>
          <li style={{ marginBottom: 4 }}>To reverse engineer, decompile, or attempt to extract the source code of the Service.</li>
          <li style={{ marginBottom: 4 }}>
            To use scripts, bots, automation, or other artificial means to inflate or manipulate
            engagement metrics such as XP, levels, streaks, daily goals, or achievement badges.
          </li>
          <li>
            In any manner that violates export-control or sanctions laws (see Section 16).
          </li>
        </ul>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>6. AI Content Disclaimer</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          <strong>Important:</strong> You are interacting with an AI system. All responses (in both
          Fast and Explain modes) are generated by high-performance open AI models. Our{" "}
          <strong>primary</strong> inference provider is <strong>Groq Cloud</strong> (running
          GPT-OSS 120B, GPT-OSS 20B and Qwen 3.6 27B on LPUs); if Groq is temporarily slow or unavailable, the same request
          automatically falls back to <strong>Mistral AI</strong> or <strong>NVIDIA NIM</strong> (70B–150B parameter models), and may then use
          <strong>Cloudflare Workers AI</strong> (70B Fast FP8) as a last-resort provider so the lesson can
          still be generated. All responses are <strong>not reviewed by humans before being shown</strong>.
          To keep the Service reliable, if the primary provider is temporarily slow or unavailable,
          the same request is automatically retried and may be routed to Mistral, NVIDIA, or, if needed, the
          Cloudflare last-resort provider. Style, depth, and tone may vary between provider paths. No human is involved
          in any path.
          Lessons are intentionally written in a warm, natural, conversational style that may feel
          like a human tutor — but every lesson, quiz, and explanation is machine-generated, and
          no human is involved in the conversation.
          The information provided may be inaccurate, incomplete, or outdated. RealLearn does not
          guarantee the accuracy, reliability, or completeness of any AI-generated content. The
          content is for educational purposes only and should not be considered professional advice
          (medical, legal, financial, etc.). Always verify important information with qualified
          professionals or authoritative sources.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>7. Intellectual Property</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          The Service and its original content, features, and functionality are owned by RealLearn
          and are protected by applicable copyright and other intellectual property laws, to the
          extent such rights exist or are registered. Your saved lessons and progress data remain
          your property, though you grant us a limited license to store and display them as part
          of the Service.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>8. Account Suspension and Termination</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          We may <strong>suspend</strong> your access to the Service at any time, including while we
          investigate suspected violations of these Terms, security incidents, or abusive behavior.
          Suspension may be temporary and may occur without prior notice where necessary to protect
          the Service or other users. We will use reasonable efforts to inform you of the reason for
          suspension unless prohibited by law or safety concerns.
        </p>
        <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
          We may <strong>terminate</strong> or suspend your access to the Service immediately, without
          prior notice or liability, for any reason, including if you breach these Terms. Upon
          termination, your right to use the Service will immediately cease. You may also terminate
          your account at any time using the &quot;Delete My Data&quot; feature. Sections of these
          Terms that by their nature should survive termination (including intellectual property,
          disclaimer of warranties, limitation of liability, indemnification, governing law, and
          dispute resolution) will survive.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>9. Disclaimer of Warranties</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          The Service is provided on an <strong>&quot;AS IS&quot; and &quot;AS AVAILABLE&quot;</strong>{" "}
          basis, without warranties of any kind, whether express, implied, or statutory. To the
          maximum extent permitted by law, RealLearn disclaims all warranties, including implied
          warranties of merchantability, fitness for a particular purpose, title, and
          non-infringement, and any warranty that the Service will be uninterrupted, error-free,
          secure, or that AI-generated content will be accurate, current, or complete. Some
          jurisdictions do not allow the exclusion of certain warranties, so some of the above
          exclusions may not apply to you; in that case, such warranties are limited to the minimum
          scope and duration permitted by law. Nothing in these Terms excludes or limits liability
          that cannot lawfully be excluded or limited, including your non-waivable statutory
          consumer rights.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>10. Limitation of Liability</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          To the maximum extent permitted by law, RealLearn shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages, or any loss of profits, data,
          or goodwill, arising out of or in connection with your use of the Service. Our total
          aggregate liability to you for all claims arising out of or relating to these Terms or
          the Service shall not exceed the greater of (a) the amount you paid us in the twelve
          months prior to the event giving rise to the claim (which is zero for our free service)
          and (b) one thousand Indian Rupees (₹1,000). The Service is provided free of charge, and
          you acknowledge that these limitations are a reasonable allocation of risk that reflects
          the free nature of the Service. Nothing in this section limits liability that cannot
          lawfully be limited.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>11. Indemnification</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          You agree to defend, indemnify, and hold harmless RealLearn, its operator, affiliates,
          officers, agents, and employees from and against any claims, liabilities, damages,
          losses, and expenses (including reasonable legal fees) arising out of or in any way
          connected with your access to or use of the Service, your violation of these Terms, your
          violation of any third-party right, or your violation of any applicable law or regulation.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>12. Content Moderation and Guardrails</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          We employ automated content filtering — a rule-based (pattern-matching) safety classifier
          that runs on our own servers, with no third-party AI call and no human in the loop at the
          moment of the check — on the questions you submit and on the AI-generated responses, to
          keep the Service safe and appropriate for all users. The filter is applied both to your
          input (before a lesson is generated) and to the generated output (before it is shown).
          Because it is automated and rule-based, it is not perfect: it may occasionally block a
          legitimate, educational question or, conversely, miss something it should have caught.
          The rules are intentionally scoped so that sensitive-but-educational topics — for example
          the history of nuclear weapons, disease and vaccination, or historical atrocities — remain
          answerable; only genuinely harmful requests (such as step-by-step instructions to cause
          harm) and always-illegal content are blocked. If you believe an educational question was
          wrongly blocked, you can rephrase it or contact us. When content is blocked or flagged, a
          moderation log entry is created recording the reason the content was flagged and the
          submitted question (capped at 500 characters), together with a pseudonymous account
          identifier; these entries may be reviewed by humans for moderation purposes and are{" "}
          <strong>automatically deleted after at most 90 days</strong> (or earlier if you delete
          your account), as described in our Privacy Policy. We also apply rate limits and
          input-size limits to protect the
          Service from abuse. We reserve the right to remove or restrict access to
          content that violates our community guidelines or these Terms. We also maintain guardrails
          to prevent the AI from generating harmful, illegal, or age-inappropriate content.
          Repeated attempts to generate prohibited content may result in suspension or termination
          of your account.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>13. Governing Law</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          These Terms shall be governed by and construed in accordance with the laws of India,
          without regard to its conflict of law provisions.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>14. Dispute Resolution</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)", marginBottom: 8 }}>
          We hope to resolve any concerns informally. If a dispute arises out of or relates to these
          Terms or your use of the Service, the party raising the dispute must first send written
          notice to the other party describing the dispute in reasonable detail. The parties will
          then negotiate in good faith for at least <strong>30 days</strong> (the &quot;Informal
          Resolution Period&quot;) before commencing any formal proceedings.
        </p>
        <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
          If the dispute is not resolved informally, the parties agree to attempt to resolve the
          dispute through non-binding mediation in <strong>Mandsaur, Madhya Pradesh, India</strong>,
          conducted in English or Hindi, in accordance with the laws of India.
        </p>
        <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
          If mediation does not resolve the dispute, either party may pursue final resolution
          through binding arbitration or litigation, at the initiating party&apos;s election,
          exclusively in the courts or arbitration forum located in{" "}
          <strong>Mandsaur, Madhya Pradesh, India</strong>. Any arbitration shall be conducted under
          the Arbitration and Conciliation Act, 1996, by a single arbitrator appointed in accordance
          with that Act. Judgment on any arbitration award may be entered in any court having
          jurisdiction. You agree that any formal dispute-resolution proceedings will be conducted
          only on an individual basis and not as a class, consolidated, or representative action.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>15. Force Majeure</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          RealLearn will not be liable or responsible to you, nor be treated as having breached these
          Terms, for any failure or delay in performing our obligations under these Terms to the
          extent the failure or delay is caused by events beyond our reasonable control, including
          but not limited to acts of God, war, terrorism, riots, embargoes, acts of civil or military
          authorities, fire, floods, earthquakes, accidents, strikes or shortages of transportation,
          facilities, fuel, energy, labor, or materials, failure of telecommunications or internet
          services, or governmental action.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>16. Export Control and Sanctions</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          You may use the Service only in compliance with all applicable export-control and economic
          sanctions laws and regulations, including those of India, the United States, the United
          Nations, the European Union, and any other jurisdiction that applies to you. You may not
          use the Service if you are located in, ordinarily resident in, or under the control of a
          country or territory that is subject to comprehensive sanctions, or if you are listed on
          any prohibited or restricted-party list. You may not use the Service for any end use that
          is prohibited by applicable export or sanctions laws, including nuclear, chemical, or
          biological weapons proliferation, or the development of missile technology.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>17. Service Availability</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          We aim to keep RealLearn available, but the Service is provided on a best-effort basis and
          we do not guarantee uninterrupted, timely, secure, or error-free operation. The Service may
          be unavailable from time to time for maintenance, upgrades, or reasons outside our control.
          We may change, suspend, or discontinue any feature or AI provider (including our use of
          Groq Cloud, Mistral AI, NVIDIA NIM, or Cloudflare Workers AI) at any time without notice or
          liability. We reserve the right to modify or remove features based on usage, cost,
          availability, safety, or legal considerations.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
         <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>18. Changes to Terms</h3>
         <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
           We reserve the right to modify or replace these Terms at any time. If a revision is
           material, we will notify you — typically by requiring you to review and re-accept the
           updated Terms in the app before continuing, and/or by an updated notice on this page.
           Revisions take effect when posted unless a later effective date is stated. What
           constitutes a material change will be determined at our sole discretion. By continuing
           to access or use the Service after any revisions become effective, you agree to be
           bound by the updated Terms; if you do not agree, you must stop using the Service.
         </p>
           <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
             <strong>Version 3.3 (effective August 17, 2026).</strong> This update updates our AI
             content disclaimer (Section 6) and service provider disclosures (Section 17) to reflect
             <strong> Mistral AI</strong> alongside Groq Cloud, NVIDIA NIM, and Cloudflare Workers AI.
             All lesson content remains machine-generated without human pre-review and is provided &quot;as is&quot;
             for educational purposes. Because this introduces a new provider disclosure, we are re-prompting
             all users to review and re-accept these Terms and our updated Privacy Policy before continuing.
           </p>
           <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
             <strong>Version 3.2 (effective August 17, 2026).</strong> This update updates our AI
             content disclaimer (Section 6) and service provider disclosures (Section 17) to reflect
             <strong> Groq Cloud</strong> as our primary AI inference provider (running open models Qwen 3.6 27B and GPT-OSS 120B on LPUs),
             <strong> NVIDIA NIM</strong> as our automatic secondary fallback, and
             <strong> Cloudflare Workers AI</strong> as our last resort. All lesson content remains machine-generated
             without human pre-review and is provided &quot;as is&quot; for educational purposes.
             Because this is a material provider disclosure change, we are re-prompting all users to
             review and re-accept these Terms and our updated Privacy Policy before continuing.
           </p>
           <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
             <strong>Version 3.1 (effective August 11, 2026).</strong> This update replaces the
             standalone &quot;Find&quot; feature described in Section 2 with an internal, quiz-driven
             personalization layer. RealLearn now builds a compact learning profile from your quiz
             results on your device and attaches a small, topic-relevant learning-context summary to
             each lesson request so the AI can personalize the answer; this summary is not stored on
             our servers. The separate &quot;Find&quot; page and its &quot;discover related
             lessons&quot; search have been removed. The AI&apos;s personalized responses are provided
             &quot;as is&quot; without any guarantee of accuracy, completeness, or suitability.
             Because this is a material change, we are re-prompting all users to review and re-accept
             these Terms before continuing.
           </p>
           <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
             <strong>Version 3.0 (effective August 10, 2026).</strong> This update adds the new{" "}
             <strong>&quot;Find&quot;</strong> feature described in Section 2. Find builds a
             personalized map of what you have proven you know (computed on your device) and
             recommends what to learn next; its optional &quot;discover related lessons&quot; search
             sends only short topic labels and your goal text to our shared, anonymous lesson cache
             and is not stored or linked to you. Find&apos;s recommendations are suggestions only and
             are provided &quot;as is&quot; without any guarantee of accuracy, completeness, or
             suitability.
           </p>
           <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
             <strong>Version 2.9 (effective August 8, 2026).</strong> This update aligns the Terms
             with the way the Service actually operates and adds standard protective clauses. It
             (1) clarifies in Section 6 that the Cloudflare last-resort AI provider may run a
             smaller Gemma model variant, so output quality can vary between provider paths;
             (2) replaces the fixed 30-day advance-notice commitment in Section 18 with in-app
             notice and re-consent for material changes; (3) restates the accessibility statement
             (Section 22) without claiming conformance with a formal standard; (4) strengthens the
             limitation of liability (Section 10) with an aggregate cap reflecting the free nature
             of the Service; and (5) adds Sections 30–34 (Entire Agreement, No Waiver, Assignment,
             No Third-Party Beneficiaries, and Time Limit on Claims). Because these are material
             changes, we are re-prompting all users to review and re-accept these Terms and the
             updated Privacy Policy before continuing.
           </p>
           <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
             <strong>Version 2.8 (effective August 7, 2026).</strong> This update adds Section 14
             (Dispute Resolution), Section 15 (Force Majeure), Section 16 (Export Control and
             Sanctions), Section 17 (Service Availability), Section 11 (Indemnification), and Section
             29 (Severability). It also expands Section 3 (Eligibility and Age Requirements) and
             Section 8 (Account Suspension and Termination) to make suspension distinct from
             termination. Because these are material changes, we are re-prompting all users to review
             and re-accept these Terms and the updated Privacy Policy before continuing.
           </p>
           <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
             <strong>Version 2.5 (effective July 22, 2026).</strong> This update adds Section 28
             (&quot;Optional Learning Personalization&quot;), describing the new optional feature that
             lets signed-in users choose learning-style preferences and add free-text notes (capped
             at 500 characters) stored only on their device. These preferences are included with each
             lesson-generation request to tailor responses and are not stored on our servers. Because
             this changes our Privacy Policy disclosures, all users are re-prompted to review and
             re-accept both documents before continuing.
           </p>
           <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
             <strong>Version 2.4 (effective July 17, 2026).</strong> This update adds Section 27
             (&quot;Optional Feedback&quot;), describing the new optional, anonymous review feature
             offered soon after a user&apos;s first completed lesson. The review is submitted with
             no account identity and stores only the rating and review text — never an IP address,
             Clerk ID, or email. The prompt is optional and never required to use the Service. This is
             a transparency update; because it introduces no new required data and no new third
             parties, existing consent remains valid.
           </p>
           <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
             <strong>Version 2.3 (effective July 14, 2026).</strong> This update describes where your
            saved lesson history is stored: the full content of every saved lesson (chat) now lives
            in your browser&apos;s <strong>IndexedDB</strong> on your own device (with only a
            lightweight history index in localStorage), and never on our servers. Clearing your
            browser&apos;s site data removes your saved lessons and we cannot restore them.
            Because our Privacy Policy changed alongside this (version 2.4), we are re-prompting
            all users to review and re-accept both documents before continuing.
          </p>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
            <strong>Version 2.7 (effective August 5, 2026).</strong> This update adds
            <strong> NVIDIA NIM</strong> as the automatic AI fallback after Cerebras and moves
            <strong> Cloudflare Workers AI</strong> to a last-resort provider role. Because this is a
            material provider-routing change, we are re-prompting all users to review and re-accept
            these Terms and the updated Privacy Policy before continuing.
          </p>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", marginTop: 8 }}>
            <strong>Version 2.2 (effective July 13, 2026).</strong> This update clarifies our AI
            inference providers: our <strong>primary</strong> provider is now{" "}
            <strong>Cerebras Cloud</strong> (running Google&apos;s Gemma 4 31B), with{" "}
            <strong>Cloudflare Workers AI</strong> (Gemma) as an automatic fallback. Because this is a
            material change, we are re-prompting all users to review and re-accept these Terms (and
            our Privacy Policy) before continuing. Lesson generation and account features that
            require current consent will be paused until you re-accept.
          </p>
        </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>19. Contact Information</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          If you have any questions about these Terms of Service or our legal policies, please
          contact us at{" "}
          <a href="mailto:esamzai365@gmail.com" style={{ color: "var(--accent)" }}>
            esamzai365@gmail.com
          </a>.
          You may also visit our website at{" "}
          <a
            href="https://reallearn.site"
            style={{ color: "var(--accent)" }}
          >
            reallearn.site
          </a>.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>20. Copyright and Trademark</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          RealLearn, the RealLearn logo, and all related names, logos, and slogans are the
          intellectual property of alakmar344 (the operator of RealLearn), to the extent such
          rights exist under applicable law. All content generated by the Service is the property
          of the user who requested it, subject to our limited license to display it as part of the
          Service. Unauthorized use of our branding is prohibited.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>21. Data Retention and Deletion</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          We retain your account and conversation data only as long as necessary to provide the
          service or comply with legal obligations. When you delete your account, we delete your
          data from our servers within 30 days. Anonymously cached lessons (used to answer repeat
          questions faster) are keyed by a hash of the question — not by your identity — and expire
          automatically, typically within a few hours. Moderation log entries expire automatically
          after at most 90 days. Saved lessons in your browser remain until you
          clear them or use the &quot;Delete My Data&quot; feature. For more details, see our{" "}
          <a href="/legal?tab=privacy" style={{ color: "var(--accent)" }}>Privacy Policy</a>.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>22. Accessibility</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          We try to make the Service usable by as many learners as possible and follow common
          accessibility practices where we can. We do not represent or warrant conformance with
          WCAG or any other formal accessibility standard. If you experience accessibility issues,
          please contact us and we will make reasonable efforts to address them.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>23. Gamification &amp; Virtual Rewards</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          The Service offers engagement features including experience points (XP), levels, daily
          streaks, streak freezes, daily goals, and achievement badges (collectively,
          &quot;Virtual Rewards&quot;). Virtual Rewards are provided for motivational and entertainment
          purposes only. They have <strong>no monetary value</strong>, cannot be purchased,
          redeemed, transferred, or exchanged for cash or any other benefit, and confer no
          ownership rights. Because this data is stored locally in your browser, it is tied to that
          browser and device and may be lost if you clear your browser data, switch devices or
          browsers, or use the &quot;Delete My Data&quot; feature. We may add, modify, reset, or
          discontinue any Virtual Reward or engagement feature at any time without notice or
          liability. Shareable result cards are generated on your device; you are responsible for
          any content you choose to share and for complying with the terms of any platform you
          share to.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>24. Voice Features</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          The Service offers optional voice input (speech-to-text) and &quot;Listen&quot; read-aloud
          (text-to-speech) features. <strong>Voice input</strong> relies on your browser&apos;s
          built-in Web Speech API: availability and accuracy depend on your browser, device, and
          language, and it may be unavailable in some browsers. It requires you to grant microphone
          permission to your browser; the microphone is used only during an active voice-input
          session and RealLearn never receives or stores your audio. Speech recognition may be
          processed by your browser vendor&apos;s speech service under that vendor&apos;s own terms.
          <strong> Listen (read-aloud)</strong> is generated by our servers using Microsoft&apos;s
          Edge neural text-to-speech service: the lesson text is synthesized into audio and streamed
          to your device, and voice availability and quality depend on the selected language and
          the third-party service. Read-aloud requests are subject to rate limits and text-length
          limits, and generated audio may be cached anonymously (see the Privacy Policy). Voice
          features are provided &quot;as is&quot; — transcription and pronunciation errors are
          possible, and you are responsible for reviewing transcribed text before submitting a
          question. We may modify or discontinue voice features at any time without liability.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>
          25. AI Safety and User Responsibility
        </h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          RealLearn includes automated safety filters, but no automated system is perfect. You agree
          not to rely on the Service for emergency, medical, legal, financial, or other high-risk
          decisions, and you are responsible for independently verifying critical information.
          You also agree not to bypass, probe, or abuse safety controls, rate limits, or account
          protections. Repeated attempts to evade safeguards may result in suspension or termination.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>
          26. Privacy Rights and Compliance
        </h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          Your privacy rights are described in our Privacy Policy, including rights available under
          applicable laws such as GDPR and U.S. state privacy laws. By using the Service, you
          acknowledge that we may process data as described there to provide the product, prevent
          abuse, and meet legal obligations. If law requires us to notify you of material compliance
          or policy changes, we will do so through in-app notice, email, or an updated legal notice.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>
          27. Optional Feedback
        </h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          Soon after you complete your first learning journey, RealLearn may invite you to leave
          an optional review — a 1–10 star rating plus free-text notes on what you liked and what we
          should improve. This feedback is <strong>entirely optional and never required</strong> to
          use the Service: you may skip it, ask to be reminded later, or dismiss it permanently, and
          doing so in no way limits your access to any feature. Any review you submit is
          <strong>anonymous</strong>: it is sent without your account identity and we store only the
          rating and the text you wrote — never your IP address, Clerk ID, or email. Once you respond
          or decline, a local flag in your browser prevents the prompt from reappearing; this flag
          lives only on your device and is removed by &quot;Delete My Data&quot;. Feedback you
          submit is provided &quot;as is&quot; and may be used to improve the Service.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>
          28. Optional Learning Personalization
        </h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          RealLearn offers optional learning personalization for signed-in users. You may select
          learning-style preferences (for example, simple language, step-by-step explanations, or
          visual analogies) and add free-text notes about how you learn best. This information is
          <strong>stored only in your browser&apos;s localStorage on your own device</strong>; it is
          not stored on our servers. It is included with each lesson-generation request so the AI can
          tailor its response to your preferences, and is then discarded. The free-text notes are
          capped at 500 characters. You can change or clear your preferences anytime in Settings, and
          &quot;Delete My Data&quot; removes them. Personalization is optional: declining or leaving
          it blank does not limit your access to any feature.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>29. Severability</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court
          of competent jurisdiction, that provision will be modified to the minimum extent necessary
          to make it valid and enforceable, or if not possible, severed from these Terms; the
          remaining provisions will continue in full force and effect.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>30. Entire Agreement</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          These Terms, together with the Privacy Policy and Cookie Policy, constitute the entire
          agreement between you and RealLearn regarding the Service and supersede all prior or
          contemporaneous understandings, communications, or agreements, whether written or oral,
          regarding the Service. No statement made in marketing material, app-store listings,
          social media, or informal communications forms part of this agreement or creates any
          warranty or commitment.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>31. No Waiver</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          Our failure to enforce any right or provision of these Terms will not be considered a
          waiver of that right or provision. Any waiver must be in writing to be effective, and a
          waiver on one occasion does not waive the same or any other provision on a future
          occasion.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>32. Assignment</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          You may not assign or transfer these Terms, or any rights or obligations under them,
          without our prior written consent; any attempted assignment in violation of this section
          is void. We may assign these Terms without restriction — for example, in connection with
          a transfer of the Service to a new operator — and these Terms will bind and benefit any
          permitted successors and assigns.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>33. No Third-Party Beneficiaries</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          These Terms are for the benefit of you and RealLearn only. Nothing in these Terms is
          intended to confer any right or remedy on any other person or entity, including our
          third-party service providers.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>34. Time Limit on Claims</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          To the extent permitted by applicable law, any claim arising out of or relating to these
          Terms or the Service must be commenced within <strong>twelve (12) months</strong> after
          the cause of action accrues; otherwise, the claim is permanently barred. This section
          does not apply where prohibited by law or to rights that cannot lawfully be limited in
          time.
        </p>
      </section>
    </article>
  );
}
