export default function TermsOfService() {
  return (
    <article
      style={{
        background: "var(--bg-card)",
        borderRadius: "var(--radius-lg)",
        padding: "32px 28px",
        border: "1px solid var(--border-subtle)",
        lineHeight: 1.7,
      }}
    >
      <h2
        style={{
          fontFamily: "var(--font-playfair)",
          fontWeight: 700,
          fontSize: 24,
          marginBottom: 16,
        }}
      >
        Terms of Service
      </h2>
      <p style={{ fontSize: 13, color: "var(--text-tertiary)", marginBottom: 24 }}>
        Last updated: July 7, 2026 (version 2.0)
      </p>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>1. Acceptance of Terms</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          By accessing or using RealLearn (&quot;the Service&quot;), you agree to be bound by these Terms of Service
          (&quot;Terms&quot;). If you do not agree to these Terms, you may not use the Service. These Terms
          apply to all visitors, users, and others who access or use the Service.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>2. Description of Service</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          RealLearn is an AI-powered educational platform that generates learning content for
          user-requested topics in two answer modes: &quot;Fast&quot; (a single direct answer part
          with a quick quiz) and &quot;Explain&quot; (a 3-part learning journey — Foundation,
          Mechanism, Real World). The service includes
          interactive quizzes, progress tracking, and multilingual support. It also includes
          optional engagement features — experience points (XP), levels, daily learning streaks,
          daily goals, achievement badges, and shareable result cards — that are stored locally on
          your device to help you build a learning habit, and optional voice features: microphone
          voice input (powered by your browser&apos;s built-in speech recognition) and
          &quot;Listen&quot; read-aloud (audio generated by our servers using Microsoft&apos;s Edge
          text-to-speech service). To improve speed, lessons may be served from a short-lived,
          anonymous server-side cache when the same question has recently been asked. RealLearn is
          intended for educational purposes only.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>3. Eligibility</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          You must be at least <strong>13 years old</strong> to use this Service (or older where your
          jurisdiction sets a higher minimum digital-consent age). By using RealLearn, you represent
          and warrant that you meet this age requirement. If you are under 18, you confirm that you
          have your parent or guardian&apos;s permission — and, where the law requires verifiable
          parental consent for minors (for example, under India&apos;s DPDP Act or COPPA), that such
          consent has been given. We do not knowingly allow children under 13 to create accounts or
          use this Service. See Section 19 of our Privacy Policy for how we handle children&apos;s data.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>4. User Accounts</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          You are responsible for safeguarding your account credentials (managed via Clerk). You
          agree to notify us immediately of any unauthorized use of your account. We are not liable
          for any loss or damage arising from your failure to comply with this security obligation.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>5. Acceptable Use</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)", marginBottom: 8 }}>
          You agree not to use the Service:
        </p>
        <ul style={{ fontSize: 14, color: "var(--text-secondary)", paddingLeft: 20, margin: 0 }}>
          <li style={{ marginBottom: 4 }}>For any unlawful purpose or in violation of any laws.</li>
          <li style={{ marginBottom: 4 }}>To harass, abuse, or harm another person or entity.</li>
          <li style={{ marginBottom: 4 }}>To generate content that is harmful, violent, sexually explicit, or discriminatory.</li>
          <li style={{ marginBottom: 4 }}>To interfere with or disrupt the integrity or performance of the Service.</li>
          <li style={{ marginBottom: 4 }}>To attempt to gain unauthorized access to the Service or related systems.</li>
          <li style={{ marginBottom: 4 }}>To reverse engineer, decompile, or attempt to extract the source code of the Service.</li>
          <li>
            To use scripts, bots, automation, or other artificial means to inflate or manipulate
            engagement metrics such as XP, levels, streaks, daily goals, or achievement badges.
          </li>
        </ul>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>6. AI Content Disclaimer</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          <strong>Important:</strong> You are interacting with an AI system. All responses (in both
          Fast and Explain modes) are generated by Google&apos;s Gemma 4 open model, hosted on
          Cloudflare Workers AI, and are <strong>not reviewed by humans before being shown</strong>.
          Lessons are intentionally written in a warm, natural, conversational style that may feel
          like a human tutor — but every lesson, quiz, and explanation is machine-generated, and
          no human is involved in the conversation.
          The information provided may be inaccurate, incomplete, or outdated. RealLearn does not
          guarantee the accuracy, reliability, or completeness of any AI-generated content. The
          content is for educational purposes only and should not be considered professional advice
          (medical, legal, financial, etc.). Always verify important information with qualified
          professionals or authoritative sources.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>7. Intellectual Property</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          The Service and its original content, features, and functionality are owned by RealLearn
          and are protected by international copyright, trademark, patent, and other intellectual
          property laws. Your saved lessons and progress data remain your property, though you
          grant us a limited license to store and display them as part of the Service.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>8. Termination</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          We may terminate or suspend your access to the Service immediately, without prior notice
          or liability, for any reason, including if you breach these Terms. Upon termination, your
          right to use the Service will immediately cease. You may also terminate your account at
          any time using the &quot;Delete My Data&quot; feature.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>9. Disclaimer of Warranties</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          The Service is provided on an <strong>&quot;AS IS&quot; and &quot;AS AVAILABLE&quot;</strong>{" "}
          basis, without warranties of any kind, whether express, implied, or statutory. To the
          maximum extent permitted by law, RealLearn disclaims all warranties, including implied
          warranties of merchantability, fitness for a particular purpose, title, and
          non-infringement, and any warranty that the Service will be uninterrupted, error-free,
          secure, or that AI-generated content will be accurate, current, or complete. Some
          jurisdictions do not allow the exclusion of certain warranties, so some of the above
          exclusions may not apply to you; in that case, such warranties are limited to the minimum
          scope and duration permitted by law. Nothing in these Terms excludes or limits liability
          that cannot lawfully be excluded or limited, including your non-waivable statutory
          consumer rights.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>10. Limitation of Liability</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          To the maximum extent permitted by law, RealLearn shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages, or any loss of profits, data,
          or goodwill, arising out of or in connection with your use of the Service. Our total
          liability to you for any claim arising out of these Terms shall not exceed the amount
          you paid us in the twelve months prior to the event giving rise to the claim (which is
          zero for our free service).
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>11. Content Moderation and Guardrails</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          We employ automated content filtering — both pattern-based filters and an AI safety
          classifier — on the questions you submit and on AI-generated responses, to ensure the
          Service remains safe and appropriate for all users. Blocked inputs and flagged responses
          are logged with a pseudonymous account identifier and may be reviewed by humans for
          moderation purposes. We also apply rate limits and input-size limits to protect the
          Service from abuse. We reserve the right to remove or restrict access to
          content that violates our community guidelines or these Terms. We also maintain guardrails
          to prevent the AI from generating harmful, illegal, or age-inappropriate content.
          Repeated attempts to generate prohibited content may result in suspension or termination
          of your account.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>12. Governing Law</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          These Terms shall be governed by and construed in accordance with the laws of India,
          without regard to its conflict of law provisions. Any disputes arising from these Terms
          or your use of the Service shall be resolved in the courts located in India.
        </p>
      </section>

      <section style={{ marginBottom: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>13. Changes to Terms</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          We reserve the right to modify or replace these Terms at any time. If a revision is
          material, we will provide at least 30 days&apos; notice prior to any new terms taking effect.
          What constitutes a material change will be determined at our sole discretion. By
          continuing to access or use the Service after any revisions become effective, you agree
          to be bound by the updated terms.
        </p>
      </section>

      <section>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>14. Contact Information</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          If you have any questions about these Terms of Service or our legal policies, please
          contact us at{" "}
          <a href="mailto:esamzai365@gmail.com" style={{ color: "var(--accent)" }}>
            esamzai365@gmail.com
          </a>.
          You may also visit our website at{" "}
          <a
            href="https://reallearn.site"
            style={{ color: "var(--accent)" }}
          >
            reallearn.site
          </a>.
        </p>
      </section>

      <section style={{ marginTop: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>15. Copyright and Trademark</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          RealLearn, the RealLearn logo, and all related names, logos, and slogans are the
          intellectual property of alakmar344. All content generated by the Service is the property
          of the user who requested it, subject to our limited license to display it as part of the
          Service. Unauthorized use of our branding is prohibited.
        </p>
      </section>

      <section style={{ marginTop: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>16. Data Retention and Deletion</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          We retain your account and conversation data only as long as necessary to provide the
          service or comply with legal obligations. When you delete your account, we delete your
          data from our servers within 30 days. Anonymously cached lessons (used to answer repeat
          questions faster) are keyed by a hash of the question — not by your identity — and expire
          automatically, typically within a few hours. Saved lessons in your browser remain until you
          clear them or use the &quot;Delete My Data&quot; feature. For more details, see our{" "}
          <a href="/legal?tab=privacy" style={{ color: "var(--accent)" }}>Privacy Policy</a>.
        </p>
      </section>

      <section style={{ marginTop: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>17. Accessibility</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          We strive to make our Service accessible to all users and aim to conform to WCAG 2.1
          Level AA standards. If you experience any accessibility issues, please contact us and
          we will make reasonable efforts to address them.
        </p>
      </section>

      <section style={{ marginTop: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>18. Gamification &amp; Virtual Rewards</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          The Service offers engagement features including experience points (XP), levels, daily
          streaks, streak freezes, daily goals, and achievement badges (collectively,
          &quot;Virtual Rewards&quot;). Virtual Rewards are provided for motivational and entertainment
          purposes only. They have <strong>no monetary value</strong>, cannot be purchased,
          redeemed, transferred, or exchanged for cash or any other benefit, and confer no
          ownership rights. Because this data is stored locally in your browser, it is tied to that
          browser and device and may be lost if you clear your browser data, switch devices or
          browsers, or use the &quot;Delete My Data&quot; feature. We may add, modify, reset, or
          discontinue any Virtual Reward or engagement feature at any time without notice or
          liability. Shareable result cards are generated on your device; you are responsible for
          any content you choose to share and for complying with the terms of any platform you
          share to.
        </p>
      </section>

      <section style={{ marginTop: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>19. Voice Features</h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          The Service offers optional voice input (speech-to-text) and &quot;Listen&quot; read-aloud
          (text-to-speech) features. <strong>Voice input</strong> relies on your browser&apos;s
          built-in Web Speech API: availability and accuracy depend on your browser, device, and
          language, and it may be unavailable in some browsers. It requires you to grant microphone
          permission to your browser; the microphone is used only during an active voice-input
          session and RealLearn never receives or stores your audio. Speech recognition may be
          processed by your browser vendor&apos;s speech service under that vendor&apos;s own terms.
          <strong> Listen (read-aloud)</strong> is generated by our servers using Microsoft&apos;s
          Edge neural text-to-speech service: the lesson text is synthesized into audio and streamed
          to your device, and voice availability and quality depend on the selected language and
          the third-party service. Read-aloud requests are subject to rate limits and text-length
          limits, and generated audio may be cached anonymously (see the Privacy Policy). Voice
          features are provided &quot;as is&quot; — transcription and pronunciation errors are
          possible, and you are responsible for reviewing transcribed text before submitting a
          question. We may modify or discontinue voice features at any time without liability.
        </p>
      </section>

      <section style={{ marginTop: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>
          20. AI Safety and User Responsibility
        </h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          RealLearn includes automated safety filters, but no automated system is perfect. You agree
          not to rely on the Service for emergency, medical, legal, financial, or other high-risk
          decisions, and you are responsible for independently verifying critical information.
          You also agree not to bypass, probe, or abuse safety controls, rate limits, or account
          protections. Repeated attempts to evade safeguards may result in suspension or termination.
        </p>
      </section>

      <section style={{ marginTop: 28 }}>
        <h3 style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>
          21. Privacy Rights and Compliance
        </h3>
        <p style={{ fontSize: 14, color: "var(--text-secondary)" }}>
          Your privacy rights are described in our Privacy Policy, including rights available under
          applicable laws such as GDPR and U.S. state privacy laws. By using the Service, you
          acknowledge that we may process data as described there to provide the product, prevent
          abuse, and meet legal obligations. If law requires us to notify you of material compliance
          or policy changes, we will do so through in-app notice, email, or an updated legal notice.
        </p>
      </section>
    </article>
  );
}
