"use client";

import { useEffect, useState } from "react";
import { useAuth, useUser } from "@clerk/nextjs";
import { usePathname } from "next/navigation";
import {
  CURRENT_PRIVACY_VERSION,
  CURRENT_TERMS_VERSION,
  isConsentCurrent,
  readLegalConsent,
  writeLegalConsent,
  type LegalConsentState,
} from "@/lib/legalConsent";

const ALLOWED_PATHS_WHEN_DECLINED = ["/sign-in", "/sign-up", "/legal"];

const POLICY_CHANGES = [
  "“Listen” read-aloud is now generated by our servers using Microsoft's Edge text-to-speech service (previously your browser's built-in voices). Only the lesson text and voice settings are sent — never your identity.",
  "Read-aloud audio may be cached anonymously (keyed by a one-way content hash, up to 24 hours) on our server and in your browser to save bandwidth.",
  "Removed ipify (api.ipify.org) from our third-party services — the app no longer performs client-side IP lookups.",
  "Added Microsoft to the third-party services list for text-to-speech processing.",
];

const TERMS_CHANGES = [
  "Voice Features section updated: “Listen” read-aloud is now a server-generated feature powered by Microsoft's Edge text-to-speech service; voice input remains browser-based.",
  "Read-aloud requests are subject to rate limits and text-length limits.",
  "Description of Service updated to reflect the new read-aloud architecture.",
];

export default function PreSignInConsent() {
  const { isSignedIn, getToken } = useAuth();
  const { user } = useUser();
  const pathname = usePathname();
  const [showConsent, setShowConsent] = useState(false);
  const [showReacceptConsent, setShowReacceptConsent] = useState(false);
  const [loading, setLoading] = useState(false);
  const [declined, setDeclined] = useState(false);

  useEffect(() => {
    const applyLocalRecord = (parsed: LegalConsentState | null) => {
      if (!parsed) {
        setShowConsent(true);
      } else if (isConsentCurrent(parsed)) {
        setShowConsent(false);
      } else if (parsed.accepted) {
        setShowReacceptConsent(true);
      } else {
        setDeclined(true);
        setShowConsent(false);
      }
    };

    const checkConsent = async () => {
      if (!isSignedIn && user === undefined) return;
      const parsed = readLegalConsent();

      // BANDWIDTH: when the local record is accepted at the current versions,
      // trust it and skip the backend status round-trip entirely. The backend
      // is only consulted when the local record is missing or stale (e.g. a
      // returning user on a new device).
      if (!isSignedIn || isConsentCurrent(parsed)) {
        applyLocalRecord(parsed);
        return;
      }

      try {
        const backendUrl = process.env.NEXT_PUBLIC_BACKEND_URL || "https://real-learn.onrender.com";
        const token = await getToken();
        const headers: Record<string, string> = {
          "Content-Type": "application/json",
        };
        if (token) {
          headers["Authorization"] = `Bearer ${token}`;
        }

        const response = await fetch(`${backendUrl}/api/legal-consent/status`, {
          method: "GET",
          headers,
        });

        if (response.ok) {
          const data = await response.json();
          const mongoAccepted =
            data.accepted &&
            data.privacyVersion === CURRENT_PRIVACY_VERSION &&
            data.termsVersion === CURRENT_TERMS_VERSION;

          if (mongoAccepted) {
            // Backend already has current consent — refresh the local record
            // so future loads skip this fetch.
            writeLegalConsent({
              accepted: true,
              timestamp: new Date().toISOString(),
              privacyVersion: CURRENT_PRIVACY_VERSION,
              termsVersion: CURRENT_TERMS_VERSION,
            });
            setShowConsent(false);
          } else if (parsed?.accepted) {
            setShowReacceptConsent(true);
          } else {
            setShowConsent(true);
          }
        } else {
          applyLocalRecord(parsed);
        }
      } catch {
        applyLocalRecord(parsed);
      }
    };

    checkConsent();
  }, [isSignedIn, getToken, user]);

  const saveConsent = async (accepted: boolean) => {
    setLoading(true);
    // Do NOT stamp syncedClerkId yet — it is only written after the backend
    // POST succeeds. Stamping it optimistically meant a failed POST (network
    // blip, cold start) left a record that claimed it was synced, so the
    // server-side consent record was permanently missing with no retry.
    const consent: LegalConsentState = {
      accepted,
      timestamp: new Date().toISOString(),
      privacyVersion: CURRENT_PRIVACY_VERSION,
      termsVersion: CURRENT_TERMS_VERSION,
    };

    writeLegalConsent(consent);

    if (accepted && isSignedIn) {
      try {
        const backendUrl =
          process.env.NEXT_PUBLIC_BACKEND_URL || "https://real-learn.onrender.com";
        const token = await getToken();
        const headers: Record<string, string> = {
          "Content-Type": "application/json",
        };
        if (token) {
          headers["Authorization"] = `Bearer ${token}`;
        }

        const response = await fetch(`${backendUrl}/api/legal-consent`, {
          method: "POST",
          headers,
          body: JSON.stringify({
            accepted: true,
            timestamp: consent.timestamp,
            email:
              user?.primaryEmailAddress?.emailAddress ||
              user?.emailAddresses?.[0]?.emailAddress ||
              "",
            privacyVersion: CURRENT_PRIVACY_VERSION,
            termsVersion: CURRENT_TERMS_VERSION,
          }),
        });
        if (response.ok && user?.id) {
          writeLegalConsent({ ...consent, syncedClerkId: user.id });
        }
      } catch {
        // best-effort — the home-page sync effect retries un-synced records
      }
    }

    setShowConsent(false);
    setShowReacceptConsent(false);
    setLoading(false);
    if (!accepted) {
      setDeclined(true);
    }
  };

  if (showConsent) {
    return (
      <div
        style={{
          position: "fixed",
          inset: 0,
          zIndex: 200,
          background: "rgba(0,0,0,0.6)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: 24,
        }}
      >
        <div
          style={{
            background: "var(--bg-card)",
            borderRadius: "var(--radius-lg)",
            padding: "32px 28px",
            maxWidth: 560,
            width: "100%",
            maxHeight: "90vh",
            overflowY: "auto",
            border: "1px solid var(--border-subtle)",
            boxShadow: "var(--shadow-lg)",
          }}
        >
          <h2
            style={{
              fontFamily: "var(--font-playfair)",
              fontWeight: 800,
              fontSize: 22,
              marginBottom: 12,
            }}
          >
            Welcome to RealLearn
          </h2>

          <div style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.7, marginBottom: 20 }}>
            <p style={{ marginBottom: 12 }}>
              RealLearn is an AI-powered educational platform that turns any question into a
              structured 3-part learning journey: <strong>Foundation</strong>, <strong>Mechanism</strong>, and{" "}
              <strong>Real World</strong>. You learn by reading, then prove understanding through quizzes
              before unlocking deeper content.
            </p>
            <p style={{ marginBottom: 12 }}>
              <strong>What we store:</strong> Your email address (via Clerk authentication), the
              questions you ask, your quiz scores, language/level preferences, consent timestamps,
              and your device IP address for security. Your saved lessons are stored locally in your
              browser.
            </p>
            <p style={{ marginBottom: 12 }}>
              <strong>Kid safety &amp; guardrails:</strong> RealLearn is intended for users 13 and older.
              We employ automated content filters to block harmful, violent, sexually explicit,
              or illegal content. We do not allow content that promotes self-harm, hate speech,
              or dangerous activities.
            </p>
            <p>
              By clicking <strong>Accept</strong>, you confirm that you are at least 13 years old and
              agree to our{" "}
              <a
                href="/legal?tab=privacy"
                style={{ color: "var(--accent)" }}
                onClick={(e) => e.stopPropagation()}
              >
                Privacy Policy
              </a>{" "}
              and{" "}
              <a
                href="/legal?tab=terms"
                style={{ color: "var(--accent)" }}
                onClick={(e) => e.stopPropagation()}
              >
                Terms of Service
              </a>.
            </p>
          </div>

          <div style={{ display: "flex", gap: 12, justifyContent: "flex-end" }}>
            <button
              type="button"
              onClick={() => saveConsent(false)}
              disabled={loading}
              style={{
                border: "1px solid var(--border-default)",
                borderRadius: "var(--radius-md)",
                padding: "10px 20px",
                fontSize: 14,
                fontWeight: 500,
                color: "var(--text-secondary)",
                background: "transparent",
                cursor: loading ? "not-allowed" : "pointer",
                opacity: loading ? 0.6 : 1,
                minHeight: 44,
              }}
            >
              Decline
            </button>
            <button
              type="button"
              onClick={() => saveConsent(true)}
              disabled={loading}
              style={{
                border: "none",
                borderRadius: "var(--radius-md)",
                padding: "10px 20px",
                fontSize: 14,
                fontWeight: 600,
                color: "var(--on-accent)",
                background: "var(--accent)",
                cursor: loading ? "not-allowed" : "pointer",
                opacity: loading ? 0.6 : 1,
                minHeight: 44,
              }}
            >
              {loading ? "Saving..." : "Accept & Continue"}
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (showReacceptConsent) {
    return (
      <div
        style={{
          position: "fixed",
          inset: 0,
          zIndex: 200,
          background: "rgba(0,0,0,0.6)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: 24,
        }}
      >
        <div
          style={{
            background: "var(--bg-card)",
            borderRadius: "var(--radius-lg)",
            padding: "32px 28px",
            maxWidth: 560,
            width: "100%",
            maxHeight: "90vh",
            overflowY: "auto",
            border: "1px solid var(--border-subtle)",
            boxShadow: "var(--shadow-lg)",
          }}
        >
          <h2
            style={{
              fontFamily: "var(--font-playfair)",
              fontWeight: 800,
              fontSize: 22,
              marginBottom: 12,
            }}
          >
            Updated Policies — Please Review
          </h2>

          <div style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.7, marginBottom: 20 }}>
            <p style={{ marginBottom: 12 }}>
              We have updated our Privacy Policy and Terms of Service. Please review the changes
              below and accept to continue using RealLearn.
            </p>

            <h3 style={{ fontWeight: 600, fontSize: 15, marginBottom: 8, marginTop: 16 }}>
              Privacy Policy Changes (v1.2 to v{CURRENT_PRIVACY_VERSION}):
            </h3>
            <ul style={{ paddingLeft: 20, margin: 0, fontSize: 14, color: "var(--text-secondary)" }}>
              {POLICY_CHANGES.map((change, index) => (
                <li key={`pp-${index}`} style={{ marginBottom: 6 }}>
                  {change}
                </li>
              ))}
            </ul>

            <h3 style={{ fontWeight: 600, fontSize: 15, marginBottom: 8, marginTop: 16 }}>
              Terms of Service Changes (v1.2 to v{CURRENT_TERMS_VERSION}):
            </h3>
            <ul style={{ paddingLeft: 20, margin: 0, fontSize: 14, color: "var(--text-secondary)" }}>
              {TERMS_CHANGES.map((change, index) => (
                <li key={`tos-${index}`} style={{ marginBottom: 6 }}>
                  {change}
                </li>
              ))}
            </ul>

            <p style={{ marginTop: 16 }}>
              By clicking <strong>Accept</strong>, you confirm that you agree to our updated{" "}
              <a
                href="/legal?tab=privacy"
                style={{ color: "var(--accent)" }}
                onClick={(e) => e.stopPropagation()}
              >
                Privacy Policy
              </a>{" "}
              and{" "}
              <a
                href="/legal?tab=terms"
                style={{ color: "var(--accent)" }}
                onClick={(e) => e.stopPropagation()}
              >
                Terms of Service
              </a>.
            </p>
          </div>

          <div style={{ display: "flex", gap: 12, justifyContent: "flex-end" }}>
            <a
              href="/legal?tab=privacy"
              style={{
                border: "1px solid var(--border-default)",
                borderRadius: "var(--radius-md)",
                padding: "10px 20px",
                fontSize: 14,
                fontWeight: 500,
                color: "var(--text-secondary)",
                textDecoration: "none",
                background: "transparent",
                minHeight: 44,
                display: "inline-flex",
                alignItems: "center",
                cursor: loading ? "not-allowed" : "pointer",
                opacity: loading ? 0.6 : 1,
              }}
            >
              Review Policies
            </a>
            <button
              type="button"
              onClick={() => saveConsent(true)}
              disabled={loading}
              style={{
                border: "none",
                borderRadius: "var(--radius-md)",
                padding: "10px 20px",
                fontSize: 14,
                fontWeight: 600,
                color: "var(--on-accent)",
                background: "var(--accent)",
                cursor: loading ? "not-allowed" : "pointer",
                opacity: loading ? 0.6 : 1,
                minHeight: 44,
              }}
            >
              {loading ? "Saving..." : "Accept & Continue"}
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (declined) {
    const isAllowedPath = ALLOWED_PATHS_WHEN_DECLINED.some((p) =>
      pathname?.startsWith(p)
    );
    if (isAllowedPath) return null;

    return (
      <div
        style={{
          position: "fixed",
          inset: 0,
          zIndex: 200,
          background: "rgba(0,0,0,0.6)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: 24,
        }}
      >
        <div
          style={{
            background: "var(--bg-card)",
            borderRadius: "var(--radius-lg)",
            padding: "32px 28px",
            maxWidth: 480,
            width: "100%",
            textAlign: "center",
            border: "1px solid var(--border-subtle)",
            boxShadow: "var(--shadow-lg)",
          }}
        >
          <h2
            style={{
              fontFamily: "var(--font-playfair)",
              fontWeight: 800,
              fontSize: 22,
              marginBottom: 12,
            }}
          >
            Consent Required
          </h2>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", marginBottom: 20, lineHeight: 1.7 }}>
            You must accept our Privacy Policy and Terms of Service to use RealLearn.
            Please review our policies and accept to continue.
          </p>
          <div style={{ display: "flex", gap: 12, justifyContent: "center" }}>
            <a
              href="/legal?tab=privacy"
              style={{
                border: "1px solid var(--border-default)",
                borderRadius: "var(--radius-md)",
                padding: "10px 20px",
                fontSize: 14,
                fontWeight: 500,
                color: "var(--text-secondary)",
                textDecoration: "none",
                background: "transparent",
                minHeight: 44,
                display: "inline-flex",
                alignItems: "center",
              }}
            >
              Review Policies
            </a>
            <button
              type="button"
              onClick={() => {
                setDeclined(false);
                setShowConsent(true);
              }}
              style={{
                border: "none",
                borderRadius: "var(--radius-md)",
                padding: "10px 20px",
                fontSize: 14,
                fontWeight: 600,
                color: "var(--on-accent)",
                background: "var(--accent)",
                cursor: "pointer",
                minHeight: 44,
              }}
            >
              Accept & Continue
            </button>
          </div>
        </div>
      </div>
    );
  }

  return null;
}
